server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
